CREATE TABLE CLIENTE (
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(50),
	TELEFONE VARCHAR(20)
);

CREATE TABLE PRODUTOS (
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(50),
	PRECO DECIMAL(20,2)
);

CREATE TABLE VENDAS (
	ID INT IDENTITY PRIMARY KEY,
	CLIENTE_ID INT FOREIGN KEY REFERENCES CLIENTE(ID),
	DATA_HORA DATETIME,
	VALOR_TOTAL DECIMAL (20,2),
);


CREATE TABLE PRODUTOS_VENDIDOS (
	ID INT IDENTITY PRIMARY KEY,
	VENDA_ID INT FOREIGN KEY REFERENCES VENDAS(ID),
	PRODUTO_ID INT FOREIGN KEY REFERENCES PRODUTOS(ID),
	QUANTIDADE INT,
	VALOR_UNITARIO DECIMAL(20,2)
);




